#!/usr/bin/env bash

set -e

cli() {
    javac -d bin/main -p $HOME/programming/binaries/picocli-4.7.3.jar --module-source-path src/main --module cx.ksim.dicelock.core,cx.ksim.dicelock.cli
    cp src/main/cx.ksim.dicelock.core/resources/* bin/main/cx.ksim.dicelock.core/
}

gui() {
	javac -d bin/main -p $HOME/programming/binaries/javafx-sdk-17.0.7/lib/ --module-source-path src/main --module cx.ksim.dicelock.core,cx.ksim.dicelock.gui
    cp src/main/cx.ksim.dicelock.gui/cx/ksim/dicelock/gui/Layout.fxml bin/main/cx.ksim.dicelock.gui/cx/ksim/dicelock/gui/
}

test() {
     javac -d bin/test -cp "bin/main/cx.ksim.dicelock.core:junit-platform-console-standalone-1.9.3.jar" `find src/test/ -name *.java`
}


if [ $# -eq 0 ]; then
    cli
    test
    exit 0
fi
case $1 in
    "cli")
	cli
	;;
    "gui")
	gui
	;;
    "test")
    	test
	;;
    *)
	echo "Unknown commands"
	exit 1
	;;
esac
# cp src/resources/* bin/main/cx.ksim.dicelock/
