#!/usr/bin/env bash

set -e

core_module=cx.ksim.dicelock.core
cli_module=cx.ksim.dicelock.cli
gui_module=cx.ksim.dicelock.gui

cli() {
    echo $@
	java -p bin/main:$PICOCLI_PATH -m $cli_module/$cli_module.DiceLockCLI
}

gui(){
	java -p bin/main:$JAVAFX_LIB_PATH -m $gui_module/$gui_module.Main
}

test() {
    java --add-opens $core_module/$core_module=ALL-UNNAMED  \
	--add-modules=$core_module                              \
	-p bin/main                                                \
	--patch-module "$core_module=$PWD/bin/test"            \
	--add-reads $core_module=ALL-UNNAMED                   \
	-jar junit-platform-console-standalone-1.9.3.jar           \
	-e junit-jupiter                                           \
	-p $core_module                                        \
	--reports-dir=reports
}

if [ $# -eq 0 ]; then
    cli
    exit 1
fi

case $1 in
    "cli")
	# Skip the first two arguments
	# which are `run` and `cli`
	cli ${@:2}
	;;
    "gui")
	gui
	;;
    "test")
    	test
	;;
    *)
	echo "Unknown commands"
	exit 1
	;;
esac
