#!/usr/bin/env bash
set -e
java --add-opens cx.ksim.dicelock.core/cx.ksim.dicelock.core=ALL-UNNAMED  \
     --add-modules=cx.ksim.dicelock.core                              \
     -p bin/main                                                \
     --patch-module "cx.ksim.dicelock.core=$PWD/bin/test"            \
     --add-reads cx.ksim.dicelock.core=ALL-UNNAMED                   \
     -jar junit-platform-console-standalone-1.9.3.jar           \
     -e junit-jupiter                                           \
     -p cx.ksim.dicelock.core                                        \
     --reports-dir=reports
