on:
  pull_request:
    branches:
      - main
jobs:
  run_test_on_linux:
    name: Test dicelock with junit-platform-console-standalone-1.9.3 on ${{matrix.os}} with java17
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Locating myself
        run : |
          pwd
          ls
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Run Console Launcher
        run: |
          javac @compile-src
          javac @compile-test
          cp src/resources/* bin/main/cx.ksim.dicelock
          java @test
      - name: Create test summary
        uses: test-summary/action@dist
        with:
          paths: reports/**/*.xml
        if: always()
